
[theme]
base="dark"
primaryColor="#7C8AFF"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false  # Disabled for download functionality
address = "0.0.0.0"
port = 5000

[browser]
gatherUsageStats = false
