
[theme]
primaryColor = "#4e89ae"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#e4ecf6"
textColor = "#1e1e1e"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true
headless = true
port = 5000

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
hideSidebarNav = false
