
[theme]
base="dark"
primaryColor="#7C8AFF"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"

[server]
enableCORS = false
enableXsrfProtection = false  # Disabled for download functionality

[browser]
gatherUsageStats = false

[deprecation]
showfileUploaderEncoding = false

[global]
disableWidgetStateDuplication = true
